### ISSUE TITLE
Add options to automatically download files on usage

### ISSUE THREAD

**Issue by TheGLander** [staticvariablejames/cookie-connoisseur#1]
This library is cool, but having every contributor for a project having to run a thing to get it working is pretty annoying, so I am thinking this should do either do
a. Automatic caching of cache-able files when they are not cached properly
b. If `.cookie-connoisseur` is not detected when `openCookieClickerPage` is invoked, it should download all the files (equivalent to `npx fetch-cookie-clicker-files`)
c. Have the package run `npx fetch-cookie-clicker-files` when the package is installed (`install` or `postinstall`)

**Comment by staticvariablejames** [comment]
Good point. Currently users also have to run `npx fetch-cookie-clicker-files` after modifying `cookie-connoisseur.config.json`. I will implement both `a` and `c`.

**Comment by staticvariablejames** [comment]
Implemented in `0.1.3`.

**Comment by staticvariablejames** [comment]
Update: since Playwright 1.38, browsers are not automatically downloaded on install, so `npx cookie-connoisseur fetch` would always fail. Therefore, I made Cookie Connoisseur also not fetch files on installation anymore, so the only option left is `a`.
