### ISSUE TITLE
Add options to use existing context or page

### ISSUE THREAD

**Issue by TheGLander** [staticvariablejames/cookie-connoisseur#2]
Currently I am trying to integrate Playwright tests and Cookie Connoisseur into Cppkies, but I ran into a problem: It's impossible to use an existing page (say, provided by a playwright test) to be navigated and set up. This means that for each test the same line for loading CC has to be there, which is not ideal. I propose that Cookie Connoisseur should support providing existing pages or contexts instead of only browsers.

(On a related note, Playwright test browse/page types are incompatible with normal Playwright browser/page types, maybe test types should be accepted too?)

**Comment by staticvariablejames** [comment]
I implemented the first one in version `0.1.3`.

The second one might be a mismatch between the versions of the packages `playwright` and `@playwright/test`; if you can reproduce it with the two packages having the same version, please open a new issue.
